# Generated by Django 4.1 on 2022-12-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAndCode',
        ),
    ]
