# Generated by Django 4.1 on 2022-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_emailandcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile-images'),
        ),
    ]
