# Generated by Django 4.1 on 2022-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_entityprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entityprofile',
            name='site',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
