# Generated by Django 4.1 on 2022-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_entityprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtest',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
