# Generated by Django 4.1 on 2022-12-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordtest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAndCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user-image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='entityprofile',
            options={'ordering': ('-id',)},
        ),
    ]
