# Generated by Django 4.1 on 2022-12-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailandcode_alter_entityprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailandcode',
            name='image',
        ),
    ]
