# Generated by Django 4.1 on 2023-01-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_emailandcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityprofile',
            name='company_type',
            field=models.BooleanField(default=True),
        ),
    ]
