# Generated by Django 4.1 on 2023-01-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_entityprofile_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, choices=[('applicant', 'Ищу работу'), ('entity', 'Ищу сотрудника'), ('main', 'Полный'), ('manager', 'Менеджер'), ('moderator', 'Модератор')], max_length=50, null=True),
        ),
    ]
