# Generated by Django 4.1 on 2022-12-12 21:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('requirements', ckeditor.fields.RichTextField()),
                ('terms', ckeditor.fields.RichTextField()),
                ('responsibilities', ckeditor.fields.RichTextField()),
                ('appeal', ckeditor.fields.RichTextField()),
                ('vip_status', models.BooleanField(default=False)),
                ('up_status_10', models.BooleanField(default=False)),
                ('vip_dead_time', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('moderation_comment', models.TextField(blank=True)),
                ('is_moderation', models.BooleanField(default=False)),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_vacancies', to='accounts.entitypersonal')),
                ('specialization', models.ManyToManyField(related_name='spec_vacancies', to='resume.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('vip_rubrics', models.ManyToManyField(blank=True, related_name='vip_rubrics_vacancies', to='resume.specialization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VacancyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_comments', to='accounts.manager')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vacancy.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_is_viewed', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_invited', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='resume.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='vacancy.vacancy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicantFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
        ),
    ]
