# Generated by Django 4.1 on 2022-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
