# Generated by Django 4.1 on 2023-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_education_alter_vacancy_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-up_time',)},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='up_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
