# Generated by Django 4.1 on 2023-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsom_payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckTransaction',
        ),
    ]
