# Generated by Django 4.1 on 2023-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsom_payment', '0002_delete_checktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreceipt',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
