# Generated by Django 4.1 on 2023-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsom_payment', '0003_alter_transactionreceipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionreceipt',
            name='cashier_no',
        ),
        migrations.AddField(
            model_name='transactionreceipt',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionreceipt',
            name='wallet',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='TransactionID',
        ),
    ]
