# Generated by Django 4.1 on 2023-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
