# Generated by Django 4.1 on 2023-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitshistory',
            name='tariff',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='termshistory',
            name='tariff',
            field=models.CharField(max_length=300),
        ),
    ]
