# Generated by Django 4.1 on 2022-12-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название позиции')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resume-images')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('agge', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('current_city', models.CharField(max_length=20)),
                ('social_media_type', models.CharField(blank=True, max_length=20)),
                ('social_media_text', models.CharField(blank=True, max_length=100)),
                ('family_position', models.BooleanField(default=False)),
                ('having_children', models.BooleanField(default=False)),
                ('business_trips', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('negotiable', models.BooleanField(blank=True, default=False)),
                ('city_for_work', models.CharField(blank=True, max_length=20)),
                ('type_of_employment', models.CharField(max_length=50)),
                ('additional_information', models.TextField(blank=True)),
                ('no_experience', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('driver_license', models.CharField(blank=True, max_length=100)),
                ('key_skills', models.TextField(blank=True)),
                ('pk_lvl', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('vip_status', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('moderation_comment', models.TextField(blank=True, null=True)),
                ('is_moderation', models.BooleanField(default=False)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('status_is_view_all', models.BooleanField(default=False)),
                ('status_is_hidden', models.BooleanField(default=False)),
                ('status_active_search', models.BooleanField(default=False)),
                ('status_variant_view', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('field_of_activity', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('work_date_from', models.CharField(max_length=50)),
                ('work_date_to', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('parent_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_spec', to='resume.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='ResumePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_comments', to='accounts.manager')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='specialization',
            field=models.ManyToManyField(related_name='spec_resumes', to='resume.specialization'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.CharField(max_length=150, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(null=True, upload_to='portfolio-images')),
                ('link', models.CharField(max_length=200, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='EntityFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_favorite', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=150)),
                ('faculty', models.CharField(max_length=150)),
                ('date_finish', models.CharField(max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CVView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvviews', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvviews', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('date_finish', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resume.resume')),
            ],
        ),
    ]
