# Generated by Django 4.1 on 2022-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_negotiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='resume-images'),
        ),
    ]
