# Generated by Django 4.1 on 2022-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_finish',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_finish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='place_of_work',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='position',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='current_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pk_lvl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='social_media_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='field_of_activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='place_of_work',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_date_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_date_to',
            field=models.CharField(max_length=100),
        ),
    ]
