# Generated by Django 4.1 on 2023-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_course_company_alter_course_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-up_time',)},
        ),
        migrations.AlterField(
            model_name='resume',
            name='up_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
