# Generated by Django 4.1 on 2023-01-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_options_alter_resume_up_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('id',)},
        ),
    ]
