# Generated by Django 4.1 on 2023-01-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayBoxTransactionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=100)),
                ('pg_payment_id', models.IntegerField(blank=True, null=True)),
                ('pg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pg_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pg_ps_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pg_ps_full_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pg_ps_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_description', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_result', models.IntegerField(blank=True, null=True)),
                ('pg_payment_date', models.DateTimeField(blank=True)),
                ('pg_can_reject', models.IntegerField(blank=True, null=True)),
                ('pg_user_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_user_contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('pg_need_email_notification', models.CharField(blank=True, max_length=150, null=True)),
                ('pg_testing_mode', models.IntegerField(blank=True, null=True)),
                ('pg_captured', models.IntegerField(blank=True, null=True)),
                ('pg_card_pan', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_salt', models.CharField(blank=True, max_length=150, null=True)),
                ('pg_sig', models.CharField(blank=True, max_length=150, null=True)),
                ('pg_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
