# Generated by Django 4.1 on 2023-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
