# Generated by Django 4.1 on 2023-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payment', '0002_alter_payboxtransactionreceipt_pg_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_card_brand',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_card_exp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_card_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
