# Generated by Django 4.1 on 2023-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payment', '0003_payboxtransactionreceipt_pg_card_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_can_reject',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_captured',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_net_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_ps_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_ps_full_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_result',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='pg_testing_mode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='payboxtransactionreceipt',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
