# Generated by Django 4.1 on 2023-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payment', '0004_alter_payboxtransactionreceipt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
