# Generated by Django 4.1 on 2023-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox_payment', '0005_payboxtransactionreceipt_pg_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_failure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_failure_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payboxtransactionreceipt',
            name='pg_need_phone_notification',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
